include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

test:1.1:
  extends:
    - .julia:1.1
    - .test
  tags:
    - nvidia
  image: nvidia/cuda:latest

test:1.2:
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia
  image: nvidia/cuda:latest

test:1.3:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia
  image: nvidia/cuda:latest

test:nightly:
  extends:
    - .julia:nightly
    - .test
  tags:
    - nvidia
  image: nvidia/cuda:latest
  allow_failure: true
